import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import jsPDF from 'jspdf';
import './ScanDetails.css';

const ScanDetails = () => {
  const { id } = useParams();
  const [scan, setScan] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchScanDetails();
  }, [id]);

  const downloadReport = (scanData) => {
    const timestamp = new Date().toLocaleString();
    const scanTime = new Date(scanData.timestamp).toLocaleString();

    // Create PDF document
    const pdf = new jsPDF();
    
    // Set font and title
    pdf.setFontSize(20);
    pdf.setFont(undefined, 'bold');
    pdf.text('REGULENSE COMPLIANCE REPORT', 20, 30);
    
    // Add separator line
    pdf.setLineWidth(0.5);
    pdf.line(20, 35, 190, 35);
    
    let yPosition = 50;
    
    // Report metadata
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'normal');
    pdf.text(`Generated: ${timestamp}`, 20, yPosition);
    yPosition += 10;
    pdf.text(`Scan ID: ${scanData.id}`, 20, yPosition);
    yPosition += 10;
    pdf.text(`Scan Date: ${scanTime}`, 20, yPosition);
    yPosition += 20;
    
    // Compliance Summary
    pdf.setFontSize(16);
    pdf.setFont(undefined, 'bold');
    pdf.text('COMPLIANCE SUMMARY', 20, yPosition);
    yPosition += 15;
    
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'normal');
    pdf.text(`Compliance Score: ${scanData.compliance_score}%`, 20, yPosition);
    yPosition += 10;
    pdf.text(`Status: ${scanData.is_compliant ? 'COMPLIANT' : 'NON-COMPLIANT'}`, 20, yPosition);
    yPosition += 10;
    pdf.text(`Processing Time: ${scanData.processing_time || 'N/A'} seconds`, 20, yPosition);
    yPosition += 20;
    
    // Extracted Fields
    pdf.setFontSize(16);
    pdf.setFont(undefined, 'bold');
    pdf.text('EXTRACTED FIELDS', 20, yPosition);
    yPosition += 15;
    
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'normal');
    
    const extractedFields = Object.entries(scanData.ocr_fields || {})
      .filter(([key]) => !['words', 'text', 'confidence', 'metadata'].includes(key));
    
    extractedFields.forEach(([key, value]) => {
      const fieldName = key.replace(/_/g, ' ').toUpperCase();
      const fieldValue = typeof value === 'object' ? JSON.stringify(value, null, 2) : value || 'N/A';
      
      // Check if we need a new page
      if (yPosition > 250) {
        pdf.addPage();
        yPosition = 30;
      }
      
      pdf.text(`${fieldName}: ${fieldValue}`, 20, yPosition);
      yPosition += 10;
    });
    
    yPosition += 10;
    
    // Violations
    pdf.setFontSize(16);
    pdf.setFont(undefined, 'bold');
    
    // Check if we need a new page for violations section
    if (yPosition > 240) {
      pdf.addPage();
      yPosition = 30;
    }
    
    pdf.text('VIOLATIONS DETECTED', 20, yPosition);
    yPosition += 15;
    
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'normal');
    
    if (scanData.violations && scanData.violations.length > 0) {
      scanData.violations.forEach((violation, index) => {
        // Check if we need a new page
        if (yPosition > 250) {
          pdf.addPage();
          yPosition = 30;
        }
        
        const violationText = `${index + 1}. ${violation.field || violation.type || 'Unknown'}: ${violation.message || violation.description || 'No description'} (${violation.severity || 'unknown'} severity)`;
        
        // Split long text into multiple lines
        const splitText = pdf.splitTextToSize(violationText, 170);
        pdf.text(splitText, 20, yPosition);
        yPosition += splitText.length * 7;
      });
    } else {
      pdf.text('No violations detected - Product is fully compliant', 20, yPosition);
    }
    
    // Add footer
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(10);
      pdf.setFont(undefined, 'italic');
      pdf.text('Report generated by Regulense Compliance System', 20, 280);
      pdf.text(`Page ${i} of ${pageCount}`, 170, 280);
    }
    
    // Save the PDF
    pdf.save(`regulense_report_${scanData.id}_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const fetchScanDetails = async () => {
    try {
      setLoading(true);
      
      // Fetch real data from the backend API
      const response = await fetch(`http://localhost:5000/api/scans/${id}`);
      
      if (!response.ok) {
        throw new Error(`Failed to fetch scan details: ${response.status}`);
      }
      
      const data = await response.json();
      
      // Transform the backend data to match the expected format
      const transformedData = {
        id: data.id,
        timestamp: data.upload_time,
        image_path: data.image_path,
        ocr_fields: data.ocr_fields || {},
        compliance_score: data.compliance_score || 0,
        violations: data.violations || [],
        is_compliant: data.is_compliant || false,
        validation_details: data.validation_details || {},
        processing_time: data.processing_time || 0
      };
      
      setScan(transformedData);
      setError(null);
    } catch (err) {
      setError('Failed to fetch scan details');
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <div className="loading">Loading scan details...</div>;
  if (error) return <div className="error">{error}</div>;
  if (!scan) return <div>No scan data available</div>;

  return (
    <div className="scan-details">
      <h2>Scan Details - ID: {scan.id}</h2>
      
      <div className="scan-summary">
        <div className="summary-item">
          <h3>Timestamp</h3>
          <p>{new Date(scan.timestamp).toLocaleString()}</p>
        </div>
        
        <div className="summary-item">
          <h3>Compliance Score</h3>
          <p className={scan.is_compliant ? 'score compliant' : 'score non-compliant'}>
            {scan.compliance_score}%
          </p>
        </div>
        
        <div className="summary-item">
          <h3>Processing Time</h3>
          <p>{scan.processing_time} seconds</p>
        </div>
        
        <div className="summary-item">
          <h3>Status</h3>
          <p className={scan.is_compliant ? 'status compliant' : 'status non-compliant'}>
            {scan.is_compliant ? 'Compliant' : 'Non-Compliant'}
          </p>
        </div>
      </div>
      
      <div className="scan-section">
        <h3>Extracted Fields</h3>
        <div className="fields-grid">
          {scan.ocr_fields?.fields ? (
            Object.entries(scan.ocr_fields.fields).map(([key, value]) => (
              <div className="field-item" key={key}>
                <label>{key.replace(/_/g, ' ').toUpperCase()}</label>
                <p>{value || 'N/A'}</p>
              </div>
            ))
          ) : (
            <p>No extracted fields available</p>
          )}
        </div>
      </div>

      <div className="scan-section">
        <h3>OCR Text</h3>
        <div className="ocr-text">
          <p><strong>Confidence:</strong> {scan.ocr_fields?.confidence ? `${(scan.ocr_fields.confidence * 100).toFixed(1)}%` : 'N/A'}</p>
          <div className="raw-text">
            <h4>Raw OCR Text:</h4>
            <pre>{scan.ocr_fields?.text || 'No text extracted'}</pre>
          </div>
        </div>
      </div>
      
      <div className="scan-section">
        <h3>Violations</h3>
        {scan.violations.length > 0 ? (
          <ul className="violations-list">
            {scan.violations.map((violation, index) => (
              <li key={index} className={`violation ${violation.severity}`}>
                <strong>{violation.field}:</strong> {violation.message}
              </li>
            ))}
          </ul>
        ) : (
          <p>No violations found. This product is fully compliant.</p>
        )}
      </div>

      <div className="scan-actions">
        <button 
          className="download-report-btn"
          onClick={() => downloadReport(scan)}
        >
          📄 Download Report
        </button>
      </div>
    </div>
  );
};

export default ScanDetails;