import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const Upload = () => {
  const navigate = useNavigate();
  const [selectedFile, setSelectedFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [dragOver, setDragOver] = useState(false);

  const handleDownloadReport = async () => {
    if (!result || !result.id) {
      alert('No scan data available for download');
      return;
    }

    try {
      // Fetch the scan details for the report
      const response = await fetch(`/api/scans/${result.id}`);
      if (!response.ok) {
        throw new Error('Failed to fetch scan data');
      }
      
      const scanData = await response.json();
      
      // Generate a simple text report (in a real app, this would be a PDF)
      const reportContent = generateTextReport(scanData);
      
      // Create and download the file
      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `compliance-report-${result.id}-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      
    } catch (err) {
      console.error('Download error:', err);
      alert('Failed to download report. Please try again.');
    }
  };

  const generateTextReport = (scanData) => {
    const timestamp = new Date().toLocaleString();
    const scanTime = new Date(scanData.upload_time).toLocaleString();
    
    return `
REGULENSE COMPLIANCE REPORT
===========================

Generated: ${timestamp}
Scan ID: ${scanData.id}
Filename: ${scanData.filename}
Scan Date: ${scanTime}

COMPLIANCE SUMMARY
==================
Compliance Score: ${scanData.compliance_score}%
Status: ${scanData.is_compliant ? 'COMPLIANT' : 'NON-COMPLIANT'}
Processing Time: ${scanData.processing_time || 'N/A'} seconds

EXTRACTED FIELDS
================
${Object.entries(scanData.ocr_fields || {}).map(([key, value]) => 
  `${key.replace(/_/g, ' ').toUpperCase()}: ${typeof value === 'object' ? JSON.stringify(value, null, 2) : value || 'N/A'}`
).join('\n')}

VIOLATIONS DETECTED
===================
${scanData.violations && scanData.violations.length > 0 
  ? scanData.violations.map((v, i) => `${i + 1}. ${v.field || v.type || 'Unknown'}: ${v.message || v.description || 'No description'} (${v.severity || 'unknown'} severity)`).join('\n')
  : 'No violations detected - Product is fully compliant'}

---
Report generated by Regulense Compliance System
    `.trim();
  };

  const handleFileSelect = (event) => {
    const file = event.target.files[0];
    processFile(file);
  };

  const handleDrop = (event) => {
    event.preventDefault();
    setDragOver(false);
    const file = event.dataTransfer.files[0];
    processFile(file);
  };

  const handleDragOver = (event) => {
    event.preventDefault();
    setDragOver(true);
  };

  const handleDragLeave = (event) => {
    event.preventDefault();
    setDragOver(false);
  };

  const processFile = (file) => {
    if (file) {
      // Validate file type
      const allowedTypes = ['image/jpeg', 'image/png', 'image/jpg'];
      if (!allowedTypes.includes(file.type)) {
        setError('Please select a valid image file (JPEG, PNG)');
        return;
      }
      
      // Validate file size (max 10MB)
      if (file.size > 10 * 1024 * 1024) {
        setError('File size must be less than 10MB');
        return;
      }
      
      setSelectedFile(file);
      setError(null);
      setResult(null);
    }
  };

  const handleUpload = async () => {
    if (!selectedFile) {
      setError('Please select a file first');
      return;
    }

    setUploading(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append('file', selectedFile);
      
      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData
      });
      
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || `Upload failed with status ${response.status}`);
      }
      
      const data = await response.json();
      
      // Transform the API response to match the expected format
      const transformedResult = {
        id: data.scan_id,
        filename: selectedFile.name,
        compliance_score: Math.round(data.compliance_score * 10) / 10, // Round to 1 decimal
        status: data.is_compliant ? 'compliant' : 'non-compliant',
        is_compliant: data.is_compliant,
        violations: data.violations || [],
        extracted_text: 'Processing completed successfully. View full details for extracted text.',
        upload_time: data.timestamp,
        processing_time: data.processing_time
      };
      
      setResult(transformedResult);
      
    } catch (err) {
      console.error('Upload error:', err);
      setError(err.message || 'Upload failed. Please try again.');
      setResult(null); // Don't show mock data on error
    } finally {
      setUploading(false);
    }
  };

  const resetUpload = () => {
    setSelectedFile(null);
    setResult(null);
    setError(null);
  };

  const formatFileSize = (bytes) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const getStatusColor = (status, score) => {
    if (status === 'compliant' || score >= 80) return 'green';
    if (score >= 60) return 'orange';
    return 'red';
  };

  const renderViolations = (violations) => {
    if (!violations || violations.length === 0) {
      return <p className="no-violations">✅ No violations detected</p>;
    }

    return (
      <div className="violations-section">
        <h4>Detected Violations:</h4>
        <ul className="violations-list">
          {violations.map((violation, index) => {
            // Handle both string and object violation formats
            let violationData;
            if (typeof violation === 'string') {
              // Parse string violations from backend
              violationData = {
                message: violation,
                field: 'General',
                severity: 'medium'
              };
            } else {
              // Handle object violations
              violationData = {
                message: violation?.message || violation,
                field: violation?.field || 'General',
                severity: violation?.severity || 'medium'
              };
            }

            return (
              <li key={index} className={`violation-item ${violationData.severity}`}>
                <div className="violation-content">
                  <div className="violation-message">
                    {violationData.message}
                  </div>
                  <div className="violation-details">
                    <span className="violation-field">
                      Field: {violationData.field}
                    </span>
                    <span className={`severity-badge ${violationData.severity}`}>
                      {violationData.severity.toUpperCase()}
                    </span>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      </div>
    );
  };

  return (
    <div className="upload-page">
      <h2>Upload Document for Compliance Check</h2>
      
      {!result ? (
        <div className="upload-section">
          <div 
            className={`upload-area ${dragOver ? 'drag-over' : ''} ${selectedFile ? 'has-file' : ''}`}
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
          >
            {selectedFile ? (
              <div className="file-selected">
                <div className="file-info">
                  <div className="file-icon">📄</div>
                  <div className="file-details">
                    <p className="file-name">{selectedFile.name}</p>
                    <p className="file-size">{formatFileSize(selectedFile.size)}</p>
                    <p className="file-type">{selectedFile.type}</p>
                  </div>
                </div>
                <button 
                  className="remove-file-btn"
                  onClick={resetUpload}
                  type="button"
                >
                  ✕ Remove
                </button>
              </div>
            ) : (
              <div className="upload-prompt">
                <div className="upload-icon">📁</div>
                <p className="upload-text">
                  Drag and drop your image here, or 
                  <label className="file-input-label">
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleFileSelect}
                      className="file-input"
                    />
                    click to browse
                  </label>
                </p>
                <p className="upload-hint">
                  Supported formats: JPEG, PNG (Max 10MB)
                </p>
              </div>
            )}
          </div>
          
          {error && (
            <div className="error-message">
              <span className="error-icon">⚠️</span>
              {error}
            </div>
          )}
          
          {selectedFile && (
            <div className="upload-actions">
              <button 
                className="upload-btn"
                onClick={handleUpload}
                disabled={uploading}
              >
                {uploading ? (
                  <>
                    <div className="spinner"></div>
                    Processing...
                  </>
                ) : (
                  'Analyze Document'
                )}
              </button>
            </div>
          )}
        </div>
      ) : (
        <div className="results-section">
          <div className="results-header">
            <h3>Analysis Results</h3>
            <button className="new-upload-btn" onClick={resetUpload}>
              Upload Another Document
            </button>
          </div>
          
          <div className="results-content">
            <div className="result-summary">
              <div className="score-display">
                <div className="score-circle">
                  <span 
                    className="score-value"
                    style={{ color: getStatusColor(result.status, result.compliance_score) }}
                  >
                    {result.compliance_score.toFixed(1)}%
                  </span>
                  <span className="score-label">Compliance Score</span>
                </div>
              </div>
              
              <div className="result-details">
                <div className="detail-item">
                  <span className="label">Filename:</span>
                  <span className="value">{result.filename}</span>
                </div>
                <div className="detail-item">
                  <span className="label">Status:</span>
                  <span 
                    className={`status-badge ${result.status}`}
                    style={{ color: getStatusColor(result.status, result.compliance_score) }}
                  >
                    {result.status === 'compliant' || result.compliance_score >= 80 ? 'Compliant' : 'Non-Compliant'}
                  </span>
                </div>
                <div className="detail-item">
                  <span className="label">Processed:</span>
                  <span className="value">{new Date(result.upload_time).toLocaleString()}</span>
                </div>
              </div>
            </div>
            
            {renderViolations(result.violations)}
            
            <div className="result-actions">
               <button 
                 className="view-details-btn"
                 onClick={() => navigate(`/scan/${result.id}`)}
               >
                 View Full Details
               </button>
               <button 
                 className="download-report-btn"
                 onClick={handleDownloadReport}
               >
                 Download Report
               </button>
             </div>

      <style jsx>{`
        .violations-section {
          margin-top: 20px;
          padding: 20px;
          background: #f8f9fa;
          border-radius: 8px;
          border-left: 4px solid #dc3545;
        }

        .violations-list {
          list-style: none;
          padding: 0;
          margin: 10px 0 0 0;
        }

        .violation-item {
          background: white;
          border: 1px solid #e9ecef;
          border-radius: 6px;
          margin-bottom: 10px;
          padding: 15px;
          border-left: 4px solid #dc3545;
        }

        .violation-item.critical {
          border-left-color: #dc3545;
        }

        .violation-item.major {
          border-left-color: #fd7e14;
        }

        .violation-item.minor {
          border-left-color: #ffc107;
        }

        .violation-content {
          display: flex;
          flex-direction: column;
          gap: 8px;
        }

        .violation-message {
          font-weight: 500;
          color: #495057;
          font-size: 14px;
          line-height: 1.4;
        }

        .violation-details {
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-wrap: wrap;
          gap: 10px;
        }

        .violation-field {
          font-size: 12px;
          color: #6c757d;
          background: #e9ecef;
          padding: 2px 8px;
          border-radius: 12px;
        }

        .severity-badge {
          padding: 4px 8px;
          border-radius: 12px;
          font-size: 11px;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }

        .severity-badge.critical {
          background: #dc3545;
          color: white;
        }

        .severity-badge.major {
          background: #fd7e14;
          color: white;
        }

        .severity-badge.minor {
          background: #ffc107;
          color: #212529;
        }

        .severity-badge.unknown {
          background: #6c757d;
          color: white;
        }
      `}</style>
          </div>
        </div>
      )}
    </div>
  );
};

export default Upload;